# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /.github/
    schedule:
      interval: daily
    target-branch: staging
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    versioning-strategy: increase
    target-branch: staging
